-- ═══════════════════════════════════════════════════════════════
-- playlist_quizzes — shared (community) MCQ quiz store
-- ---------------------------------------------------------------
-- Project: bhhxulecdpqnsiaogmoc
-- Client:  js/playlist-quizzes.js  (public anon key, RLS-protected)
--
-- When any user turns a video's AI quiz into a mock/MCQ test ("Take as
-- Test"), the quiz is published here keyed by VIDEO id. Every Pro user who
-- has that video inside a playlist in their own Playlist Organiser then sees
-- it in the Quiz tab's "Available" sub-tab.
--
-- Keyed by video, not playlist, on purpose: the video -> playlist mapping is
-- resolved on each reader's side from their own ytoLibrary, so a quiz made by
-- anyone reaches everyone who added a playlist containing that video, without
-- knowing the playlist at generation time.
--
-- Run once in the SQL editor of the project above. Without this table every
-- publish fails silently: publish() only console.warns, and the local
-- ez_pl_quizzes copy still succeeds, so nothing looks broken.
-- ═══════════════════════════════════════════════════════════════

create table if not exists playlist_quizzes (
  id              bigint generated by default as identity primary key,
  video_id        text not null unique,   -- upsert target (onConflict: video_id)
  title           text,
  exam            text,
  -- { questions: [engine format], correct_score, negative_score }
  quiz_data       jsonb not null default '{}'::jsonb,
  question_count  int  default 0,
  created_by      text,                   -- Firebase uid / email, or device id
  created_by_name text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- listForUser() filters by created_by and orders by updated_at; listForVideos()
-- filters by video_id (already unique, so it is indexed).
create index if not exists playlist_quizzes_created_by_updated_at_idx
  on playlist_quizzes (created_by, updated_at desc);

alter table playlist_quizzes enable row level security;

-- The app authenticates with Firebase, not Supabase, so there is no Supabase
-- JWT to match on: every request arrives as the anon role. These policies
-- reproduce exactly the access the shipped client already relies on.
do $$
begin
  if not exists (select 1 from pg_policies
                 where tablename = 'playlist_quizzes' and policyname = 'read playlist quizzes') then
    create policy "read playlist quizzes" on playlist_quizzes
      for select using (true);
  end if;

  if not exists (select 1 from pg_policies
                 where tablename = 'playlist_quizzes' and policyname = 'insert playlist quizzes') then
    create policy "insert playlist quizzes" on playlist_quizzes
      for insert with check (true);
  end if;

  -- NOTE: publish() is an upsert on video_id, and ANY user may regenerate the
  -- quiz for a video, so update cannot be restricted to created_by without
  -- breaking a second user's refresh of the same video. The trade-off is that
  -- any holder of the public anon key can overwrite any published quiz.
  -- Tightening this needs a real per-user identity (a Supabase JWT, or moving
  -- publishing behind an authenticated proxy endpoint) rather than a stricter
  -- policy alone.
  if not exists (select 1 from pg_policies
                 where tablename = 'playlist_quizzes' and policyname = 'update playlist quizzes') then
    create policy "update playlist quizzes" on playlist_quizzes
      for update using (true) with check (true);
  end if;
end $$;
