-- ═══════════════════════════════════════════════════════════════
-- question_reports + question_corrections — report a bad question, then fix it
-- ---------------------------------------------------------------
-- Project: bhhxulecdpqnsiaogmoc
-- Clients: js/question-fix.js          (engine + admin + editor, anon key)
--          youtube-turbo-proxy/app.py  (_update_report_status, PATCHes
--                                       question_reports.status by unique_key
--                                       when an admin taps the Telegram button)
--
-- question_corrections is applied by the quiz engine AT RENDER TIME, overriding
-- the question text/options/answer shown to students.
-- ═══════════════════════════════════════════════════════════════

create table if not exists question_reports (
  id                bigint generated by default as identity primary key,
  quiz_id           text,
  question_id       text,
  unique_key        text not null,      -- quizId_questionId (proxy PATCHes on this)
  quiz_title        text,
  reason            text,
  details           text,
  reported_by_email text,
  reported_by_name  text,
  question_data     jsonb default '{}'::jsonb,
  report_link       text,
  status            text default 'open',   -- open | fixed | dismissed
  created_at        timestamptz default now()
);

-- Reports are NOT unique per question on purpose: several students may report
-- the same question, and getReportByKey() takes the newest of them.
create index if not exists question_reports_unique_key_created_at_idx
  on question_reports (unique_key, created_at desc);
create index if not exists question_reports_status_created_at_idx
  on question_reports (status, created_at desc);

create table if not exists question_corrections (
  id             bigint generated by default as identity primary key,
  quiz_id        text,
  question_id    text,
  unique_key     text not null unique,   -- upsert conflict target
  -- Overriding fields only: question, option_1..n, answer, explanation, …
  corrected_data jsonb not null default '{}'::jsonb,
  fixed_by       text,
  updated_at     timestamptz default now()
);

-- getCorrectionsForQuiz() fetches every correction for a quiz in one call.
create index if not exists question_corrections_quiz_id_idx
  on question_corrections (quiz_id);

alter table question_reports     enable row level security;
alter table question_corrections enable row level security;

do $$
begin
  -- Reports: any student may file one; admin panel lists them and sets status.
  if not exists (select 1 from pg_policies
                 where tablename = 'question_reports' and policyname = 'read question reports') then
    create policy "read question reports" on question_reports for select using (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'question_reports' and policyname = 'insert question reports') then
    create policy "insert question reports" on question_reports for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'question_reports' and policyname = 'update question reports') then
    create policy "update question reports" on question_reports for update using (true) with check (true);
  end if;

  -- Corrections must be READABLE by everyone: the engine applies them when
  -- rendering a quiz.
  if not exists (select 1 from pg_policies
                 where tablename = 'question_corrections' and policyname = 'read question corrections') then
    create policy "read question corrections" on question_corrections for select using (true);
  end if;

  -- ⚠ SECURITY: these two grant WRITE access to the public anon key, because
  -- admin.html / editor.html save corrections straight from the browser. Since
  -- corrections override the question and ANSWER a student sees, anyone holding
  -- the anon key (it ships in every page) could rewrite quiz answers. The UI
  -- gate in admin.html is not a security boundary.
  --
  -- Prefer NOT to create these two policies, and instead route saveCorrection()
  -- through an authenticated proxy endpoint using the service_role key. They are
  -- included only because the currently shipped client needs them; drop them as
  -- soon as correction writes move server-side.
  if not exists (select 1 from pg_policies
                 where tablename = 'question_corrections' and policyname = 'insert question corrections') then
    create policy "insert question corrections" on question_corrections for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'question_corrections' and policyname = 'update question corrections') then
    create policy "update question corrections" on question_corrections for update using (true) with check (true);
  end if;
end $$;
