-- ═══════════════════════════════════════════════════════════════
-- quiz_attempts — in-app quiz attempt history (cross-device)
-- ---------------------------------------------------------------
-- Project: bhhxulecdpqnsiaogmoc
-- Client:  js/quiz-attempts.js  (public anon key, RLS-protected)
--
-- Separate from mock_attempts: this table holds attempts taken inside the app
-- (Saved Questions / practice), while mock_attempts holds full mock and
-- comprehensive-MCQ attempts submitted by the standalone exam engine. Note the
-- two use DIFFERENT timestamp columns — attempted_at here, submitted_at there.
--
-- Schema mirrors the block documented at the top of js/quiz-attempts.js.
-- ═══════════════════════════════════════════════════════════════

create table if not exists quiz_attempts (
  id           bigint generated by default as identity primary key,
  user_id      text not null,
  user_email   text,
  attempt_id   text not null,          -- client id, e.g. att_...
  scope        text,                   -- 'all' or a source test_id
  title        text,
  score        numeric default 0,
  max_score    numeric default 0,
  correct      int default 0,
  wrong        int default 0,
  skip         int default 0,
  total        int default 0,
  accuracy     int default 0,
  time_taken   int default 0,
  attempt_data jsonb not null default '{}'::jsonb,   -- items, answers, byQuiz
  attempted_at timestamptz default now(),
  unique (user_id, attempt_id)         -- client-supplied id makes retries idempotent
);

create index if not exists quiz_attempts_user_attempted_at_idx
  on quiz_attempts (user_id, attempted_at desc);

alter table quiz_attempts enable row level security;

-- As with saved_questions: Firebase auth means every request is the anon role,
-- so rows are separated by the user_id value rather than by caller identity.
-- See the note in supabase/saved_questions.sql.
do $$
begin
  if not exists (select 1 from pg_policies
                 where tablename = 'quiz_attempts' and policyname = 'read quiz attempts') then
    create policy "read quiz attempts" on quiz_attempts for select using (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'quiz_attempts' and policyname = 'insert quiz attempts') then
    create policy "insert quiz attempts" on quiz_attempts for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'quiz_attempts' and policyname = 'update quiz attempts') then
    create policy "update quiz attempts" on quiz_attempts for update using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'quiz_attempts' and policyname = 'delete quiz attempts') then
    create policy "delete quiz attempts" on quiz_attempts for delete using (true);
  end if;
end $$;
