-- ═══════════════════════════════════════════════════════════════
-- saved_questions — per-user bookmarked questions
-- ---------------------------------------------------------------
-- Project: bhhxulecdpqnsiaogmoc
-- Client:  js/saved-questions.js  (public anon key, RLS-protected)
--          used by BOTH test-engine.html and app.html
--
-- Column names and the conflict target are dictated by the shipped client:
--   save()   upsert(row, { onConflict: 'user_id,unique_key' })
--   remove() delete().eq('user_id', uid).eq('unique_key', uKey)
--   list()   select('*').eq('user_id', uid).order('saved_at', desc)
-- so the unique constraint MUST be (user_id, unique_key) and the timestamp
-- column MUST be named saved_at.
-- ═══════════════════════════════════════════════════════════════

create table if not exists saved_questions (
  id            bigint generated by default as identity primary key,
  user_id       text not null,          -- Firebase uid | email | device id
  user_email    text,
  test_id       text,
  question_id   text,
  unique_key    text not null,          -- testId_questionId
  quiz_title    text,
  question_data jsonb not null default '{}'::jsonb,
  saved_at      timestamptz default now(),
  unique (user_id, unique_key)          -- upsert conflict target
);

-- list() always filters by user_id and sorts by saved_at.
create index if not exists saved_questions_user_saved_at_idx
  on saved_questions (user_id, saved_at desc);

alter table saved_questions enable row level security;

-- The app signs in with Firebase, not Supabase, so every request arrives as the
-- anon role and policies cannot reference auth.uid(). These reproduce exactly
-- the access the shipped client needs.
--
-- ⚠ Consequence to be aware of: rows are only separated by the user_id VALUE in
-- the row, not by the caller's identity. Any holder of the public anon key can
-- read or delete another user's saved questions by supplying their user_id.
-- Closing that needs a real per-user identity (a Supabase JWT, or routing these
-- writes through an authenticated proxy endpoint), not a stricter policy alone.
do $$
begin
  if not exists (select 1 from pg_policies
                 where tablename = 'saved_questions' and policyname = 'read saved questions') then
    create policy "read saved questions" on saved_questions for select using (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'saved_questions' and policyname = 'insert saved questions') then
    create policy "insert saved questions" on saved_questions for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'saved_questions' and policyname = 'update saved questions') then
    create policy "update saved questions" on saved_questions for update using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies
                 where tablename = 'saved_questions' and policyname = 'delete saved questions') then
    create policy "delete saved questions" on saved_questions for delete using (true);
  end if;
end $$;
