/* ═══════════════════════════════════════════════════════════════
   PLAYLIST QUIZZES — shared (community) quiz store
   ---------------------------------------------------------------
   When any user generates a mock/MCQ test from a YouTube video (via the
   AI tutor "Take as Test"), the quiz is PUBLISHED here keyed by the
   video id. Every (Pro) user who has that video inside a playlist they
   added in the Playlist Organiser then sees the quiz in the Quiz tab's
   "Available" sub-tab, grouped under that playlist's name.

   Keyed by video (not playlist) on purpose: the video→playlist mapping
   is resolved on each reader's side from their own ytoLibrary, so a
   quiz made by anyone reaches everyone who added a playlist with that
   video — no need to know the playlist at generation time.

   ⚠ THIS MODULE USES A DIFFERENT SUPABASE PROJECT to the other quiz
   modules. Shared MCQ quizzes live in the bhhxulecdpqnsiaogmoc project;
   saved-questions.js, quiz-attempts.js, question-fix.js and
   supabase-config.js still point at deefmrmmjlknotzpceqp. Do NOT "fix"
   the difference by copying a URL/key across from one of those files —
   that would send published quizzes to a project with no
   playlist_quizzes table, and every write fails SILENTLY here (publish()
   only console.warns, and the local ez_pl_quizzes copy still succeeds,
   so the loss is invisible).

   Schema + RLS for this table: supabase/playlist_quizzes.sql

   Structurally still mirrors js/saved-questions.js: public anon key,
   RLS-protected, dedicated persistSession:false client.

   Exposes window.PlaylistQuizzes:
     .available()              -> bool
     .publish(opts)            -> Promise<bool>   (upsert by video_id)
     .listForVideos(ids[])     -> Promise<row[]>
     .listForUser(userId)      -> Promise<row[]>  (your own quizzes, any device)

   ─── Supabase schema (run once in the SQL editor) ───────────────
   create table if not exists playlist_quizzes (
     id              bigint generated by default as identity primary key,
     video_id        text not null unique,
     title           text,
     exam            text,
     quiz_data       jsonb not null default '{}'::jsonb,  -- { questions:[engine fmt], correct_score, negative_score }
     question_count  int  default 0,
     created_by      text,
     created_by_name text,
     created_at      timestamptz default now(),
     updated_at      timestamptz default now()
   );
   alter table playlist_quizzes enable row level security;
   create policy "read playlist quizzes"   on playlist_quizzes for select using (true);
   create policy "insert playlist quizzes" on playlist_quizzes for insert with check (true);
   create policy "update playlist quizzes" on playlist_quizzes for update using (true) with check (true);
   ═══════════════════════════════════════════════════════════════ */
(function () {
  // Shared MCQ quiz project. anon/public key — RLS-protected, safe in the
  // browser. See the warning above before changing either value.
  var SUPA_URL  = 'https://bhhxulecdpqnsiaogmoc.supabase.co';
  var SUPA_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoaHh1bGVjZHBxbnNpYW9nbW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MjQ2MTYsImV4cCI6MjA5ODEwMDYxNn0.vdqIwXiIx9OSIoiBkX_o78MbYSDp5dN6303xKuXn4P4';

  var _client = null;
  function client() {
    if (_client) return _client;
    if (!(window.supabase && typeof window.supabase.createClient === 'function')) {
      console.warn('[playlist-quizzes] Supabase JS library not loaded');
      return null;
    }
    _client = window.supabase.createClient(SUPA_URL, SUPA_ANON, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    return _client;
  }

  function userId() {
    try {
      var id = localStorage.getItem('ez_user_uid') || localStorage.getItem('ez_user_email');
      if (id) return id;
      var dev = localStorage.getItem('ez_device_id');
      if (!dev) { dev = 'dev_' + Math.random().toString(36).slice(2) + Date.now().toString(36); localStorage.setItem('ez_device_id', dev); }
      return dev;
    } catch (e) { return null; }
  }
  function userName() {
    try { return localStorage.getItem('ez_user_name') || localStorage.getItem('ez_user_email') || 'A learner'; } catch (e) { return 'A learner'; }
  }

  var PlaylistQuizzes = {
    available: function () { return !!client(); },

    /* Publish (or refresh) the shared quiz for a video. opts:
         { videoId, title, questions:[engine fmt], correct, negative, exam } */
    publish: async function (opts) {
      var c = client();
      if (!c || !opts || !opts.videoId) return false;
      var qs = opts.questions || [];
      if (!qs.length) return false;
      var row = {
        video_id:        String(opts.videoId),
        title:           opts.title || 'MCQ Test',
        exam:            opts.exam || null,
        quiz_data:       { questions: qs, correct_score: (opts.correct != null ? opts.correct : 2), negative_score: (opts.negative != null ? opts.negative : 0.5) },
        question_count:  qs.length,
        created_by:      userId(),
        created_by_name: userName(),
        updated_at:      new Date().toISOString()
      };
      try {
        var res = await c.from('playlist_quizzes').upsert(row, { onConflict: 'video_id' });
        if (res.error) { console.warn('[playlist-quizzes] publish failed:', res.error.message); return false; }
        return true;
      } catch (e) { console.warn('[playlist-quizzes] publish threw:', e); return false; }
    },

    /* All shared quizzes for the given video ids (chunked to keep the URL short). */
    listForVideos: async function (videoIds) {
      var c = client();
      if (!c || !videoIds || !videoIds.length) return [];
      // de-dupe + chunk
      var uniq = Object.keys((videoIds || []).reduce(function (m, v) { if (v) m[v] = 1; return m; }, {}));
      var out = [], CHUNK = 100;
      try {
        for (var i = 0; i < uniq.length; i += CHUNK) {
          var slice = uniq.slice(i, i + CHUNK);
          var res = await c.from('playlist_quizzes').select('*').in('video_id', slice);
          if (res.error) { console.warn('[playlist-quizzes] listForVideos failed:', res.error.message); continue; }
          out = out.concat(res.data || []);
        }
      } catch (e) { console.warn('[playlist-quizzes] listForVideos threw:', e); }
      return out;
    },

    /* Every quiz the given user generated, newest first — regardless of which
       playlist (or none) the source video belongs to. This is what powers
       cross-device sync: sign in on any device and the quizzes you made come
       back. Requires a stable account id (Firebase uid / email); a per-device
       fallback id would not match across devices. */
    listForUser: async function (uid) {
      var c = client();
      if (!c || !uid) return [];
      try {
        var res = await c.from('playlist_quizzes')
          .select('*')
          .eq('created_by', String(uid))
          .order('updated_at', { ascending: false })
          .limit(200);
        if (res.error) { console.warn('[playlist-quizzes] listForUser failed:', res.error.message); return []; }
        return res.data || [];
      } catch (e) { console.warn('[playlist-quizzes] listForUser threw:', e); return []; }
    }
  };

  window.PlaylistQuizzes = PlaylistQuizzes;
})();
