import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import tailwindcss from '@tailwindcss/vite';

const rootDir = resolve(import.meta.dirname);
const outDir = resolve(rootDir, 'dist');
const legacyDirectories = ['css', 'js', 'pages', 'demo', 'assets'];
// test-engine.html is a self-contained page (inline scripts + CDN + relative
// legacy js). It is copied as-is rather than added as a Vite entry, because Vite
// would try to bundle its <script src="js/supabase-config.js"> (an optional file
// that may be absent) and fail the build. Copying keeps it working standalone and
// makes it reachable at /Examen-planner/test-engine.html in production.
// editor.html is the standalone StudyPlanner question editor (opened from the
// Telegram report buttons, in a browser or as a Telegram Mini App). Like
// test-engine.html it is self-contained (inline JS + CDN + relative legacy js),
// so it is copied as-is rather than added as a Vite bundle entry.
const legacyFiles = ['test-engine.html', 'editor.html'];
const appBase = '/Examen-planner/';

function listBuiltFiles(directory, prefix = '') {
  return readdirSync(directory).flatMap((name) => {
    const absolute = resolve(directory, name);
    const relative = prefix ? `${prefix}/${name}` : name;
    return statSync(absolute).isDirectory()
      ? listBuiltFiles(absolute, relative)
      : [relative];
  });
}

function collectPrecacheUrls(files) {
  const urls = new Set(files.map((file) => appBase + file.split('/').map(encodeURIComponent).join('/')));
  const origin = 'https://studyplanner.invalid';

  files.filter((file) => file.endsWith('.html')).forEach((file) => {
    const html = readFileSync(resolve(outDir, file), 'utf8');
    const baseUrl = new URL(appBase + file, origin);
    const references = html.matchAll(/(?:href|src|data-include)\s*=\s*["']([^"']+)["']/g);
    for (const match of references) {
      const value = match[1];
      if (!value || /\$\{|\{\{|<%/.test(value) || /^(?:data:|https?:|\/\/|#|mailto:|tel:)/i.test(value)) continue;
      try {
        const resolvedUrl = new URL(value, baseUrl);
        if (resolvedUrl.origin === origin && resolvedUrl.pathname.startsWith(appBase)) {
          urls.add(resolvedUrl.pathname + resolvedUrl.search);
        }
      } catch (error) {}
    }
  });

  return Array.from(urls).sort();
}

function writeOfflineServiceWorker() {
  const files = listBuiltFiles(outDir)
    .filter((file) => file !== 'sw.js' && !file.endsWith('.map'))
    .sort();
  const urls = collectPrecacheUrls(files);
  const revisions = files.map((file) => ({
    file,
    revision: createHash('sha256').update(readFileSync(resolve(outDir, file))).digest('hex').slice(0, 16)
  }));
  const version = createHash('sha256')
    .update(JSON.stringify({ revisions, urls }))
    .digest('hex')
    .slice(0, 12);
  const source = `/* Generated by Vite. Do not edit dist/sw.js directly. */
const CACHE_PREFIX = 'studyplanner-shell-';
const CACHE_NAME = CACHE_PREFIX + '${version}';
const APP_BASE = '${appBase}';
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(PRECACHE_URLS.map(async (url) => {
      try { await cache.add(new Request(url, { cache: 'reload' })); }
      catch (error) { console.warn('[sw] precache skipped', url, error); }
    }));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

async function fetchWithTimeout(request, timeoutMs) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try { return await fetch(request, { signal: controller.signal }); }
  finally { clearTimeout(timer); }
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetchWithTimeout(request, 4000);
    if (response && response.ok) await cache.put(request, response.clone());
    return response;
  } catch (error) {
    return (await cache.match(request, { ignoreSearch: true }))
      || (await cache.match(APP_BASE + 'app.html'))
      || (await cache.match(APP_BASE + 'index.html'))
      || Response.error();
  }
}

async function cacheFirst(request, event) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  const refresh = fetch(request).then(async (response) => {
    if (response && response.ok) await cache.put(request, response.clone());
    return response;
  }).catch(() => null);
  if (cached) {
    event.waitUntil(refresh);
    return cached;
  }
  return (await refresh) || Response.error();
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(networkFirst(request));
    return;
  }
  const isStatic = ['script', 'style', 'image', 'font'].includes(request.destination)
    || ['assets/', 'css/', 'js/', 'pages/', 'vendor/'].some((dir) => url.pathname.startsWith(APP_BASE + dir));
  if (isStatic) event.respondWith(cacheFirst(request, event));
});
`;
  writeFileSync(resolve(outDir, 'sw.js'), source);
  console.log(`  ✓ Generated sw.js with ${urls.length} precached files (${version})`);
}

function copyLegacyStaticAssets() {
  return {
    name: 'copy-legacy-static-assets',
    apply: 'build',
    enforce: 'post',
    closeBundle() {
      console.log('📋 Copying legacy assets to dist...');
      mkdirSync(outDir, { recursive: true });

      legacyDirectories.forEach((dir) => {
        const from = resolve(rootDir, dir);
        const to = resolve(outDir, dir);
        if (existsSync(from)) {
          console.log(`  ✓ Copying ${dir}/ → dist/${dir}/`);
          cpSync(from, to, { recursive: true, force: true });
        }
      });

      legacyFiles.forEach((file) => {
        const from = resolve(rootDir, file);
        const to = resolve(outDir, file);
        if (existsSync(from)) {
          if (file.endsWith('.html')) {
            const html = readFileSync(from, 'utf8').replace(
              /((?:src)\s*=\s*["'])(vendor\/[^"'?]+\.js)(?:\?[^"']*)?(["'])/g,
              (whole, pre, url, post) => {
                const vendorFile = resolve(rootDir, 'public', url);
                if (!existsSync(vendorFile)) return whole;
                const hash = createHash('sha256').update(readFileSync(vendorFile)).digest('hex').slice(0, 8);
                return `${pre}${url}?v=${hash}${post}`;
              }
            );
            writeFileSync(to, html);
          } else {
            cpSync(from, to, { force: true });
          }
          console.log(`  ✓ Copying ${file} → dist/${file}`);
        }
      });
      
      writeOfflineServiceWorker();
      console.log('✅ Legacy assets copied and offline shell generated successfully!');
    }
  };
}

// ── Automated cache-busting ────────────────────────────────────────────────
// Vite already content-hashes assets that live in its module graph (the
// `type="module"` entry src/main.js and every <link rel="stylesheet">). But
// this app also loads ~50 classic `<script src="js/...">` files and its HTML
// partials via `data-include="pages/*.html"` — neither is seen by Vite, so
// historically each carried a HAND-TYPED `?v=YYYYMMDDx` token that had to be
// bumped manually on every edit. Forgetting to bump left browsers/CDN serving
// a stale cached copy ("I changed it but the URL is the same").
//
// This plugin removes that manual step: at build time it rewrites every local
// js/ and pages/ reference in the emitted HTML to `?v=<contentHash>`, where the
// hash is the first 8 hex chars of the file's SHA-256. The URL therefore
// changes if and ONLY if that specific file's bytes change — so unchanged files
// stay cached (fast for mobile users) and edited files always cache-bust.
// Source HTML keeps the bare `href="js/..."` / `data-include="pages/..."`; the
// version is injected only into the built output.
function contentHashCacheBust() {
  const hashCache = new Map();
  const hashFor = (relPath) => {
    if (hashCache.has(relPath)) return hashCache.get(relPath);
    let hash = null;
    try {
      const sourcePath = relPath.startsWith('vendor/')
        ? resolve(rootDir, 'public', relPath)
        : resolve(rootDir, relPath);
      const bytes = readFileSync(sourcePath);
      hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8);
    } catch {
      hash = null; // referenced file not on disk → leave unversioned
    }
    hashCache.set(relPath, hash);
    return hash;
  };

  return {
    name: 'content-hash-cache-bust',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler(html) {
        return html.replace(
          /((?:href|src|data-include)\s*=\s*["'])([^"']+)(["'])/g,
          (whole, pre, url, post) => {
            // Skip external / protocol-relative / data URLs and Vite's own
            // already-hashed bundle output under assets/.
            if (/^(?:https?:)?\/\//i.test(url) || url.startsWith('data:')) return whole;
            const path = url.split('?')[0].split('#')[0];
            // Only bust the two categories Vite can't fingerprint itself.
            if (!/(?:^|\/)(?:js|pages|css|vendor)\/[^?#]+\.(?:js|html|css)$/.test(path)) return whole;
            // Normalise to a source-relative path by dropping any leading base
            // prefix (e.g. "/Examen-planner/") or "./" before the managed dir.
            const rel = path.replace(/^.*?(?=(?:js|pages|css|vendor)\/)/, '');
            const hash = hashFor(rel);
            // Rebuild with a clean single ?v=; if the file is missing, emit the
            // reference without any stale query string.
            return pre + path + (hash ? '?v=' + hash : '') + post;
          }
        );
      }
    }
  };
}

export default defineConfig({
  // GitHub Pages serves this project from /Examen-planner/, not the domain
  // root. Vite defaults to absolute root-relative asset paths (/assets/...),
  // which 404 on a project Pages site and leave the deployed app unstyled.
  // Setting `base` scopes every built <script>/<link> reference to the
  // correct subpath so CSS/JS actually load in production.
  base: appBase,
  appType: 'mpa',
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        index: resolve(rootDir, 'index.html'),
        app: resolve(rootDir, 'app.html'),
        admin: resolve(rootDir, 'admin.html'),
        ytProxyDemo: resolve(rootDir, 'yt-proxy-demo.html'),
        opencodeDemo: resolve(rootDir, 'opencode-demo.html')
      }
    }
  },
  plugins: [tailwindcss(), contentHashCacheBust(), copyLegacyStaticAssets()]
});
