/* PrepPath Admin — FINTECH PRESENTATION LAYER
   Wraps the existing renderers after they run, preserving every generated ID,
   inline action, filter read and backend contract. Loaded last. */

var FIN_ORIGINAL_RENDERERS = {
  analytics: renderAnalytics,
  pending: renderPending,
  users: renderUsers,
  plans: renderPlans,
  payments: renderPayments,
  referrals: renderReferrals,
  payouts: renderPayouts,
  coupons: renderCoupons,
  requests: renderRequests,
  reports: renderReports,
  telegram: renderTelegram,
  settings: renderSettings
};

var FIN_VIEW_META = {
  analytics: {
    eyebrow: 'Executive overview',
    title: 'Business control center',
    description: 'A live operating view of acquisition, revenue and every queue that needs attention.'
  },
  pending: {
    eyebrow: 'Identity operations',
    title: 'Approval desk',
    description: 'Review registrations quickly while keeping duplicate-device and account-risk signals visible.'
  },
  users: {
    eyebrow: 'Customer operations',
    title: 'Account portfolio',
    description: 'Search, segment and manage user access, subscriptions, trials and registered devices.'
  },
  plans: {
    eyebrow: 'Revenue configuration',
    title: 'Plans and pricing desk',
    description: 'Operate pricing, UPI collection details, free-tier limits and upcoming renewals in one place.'
  },
  payments: {
    eyebrow: 'Revenue assurance',
    title: 'Payment operations',
    description: 'Verify incoming transactions, investigate duplicate IDs and reconcile collected revenue.'
  },
  referrals: {
    eyebrow: 'Growth operations',
    title: 'Referral network',
    description: 'Measure invitation activity, paid conversion and the rewards generated by each advocate.'
  },
  payouts: {
    eyebrow: 'Partner finance',
    title: 'Payout control',
    description: 'See unlocked rewards, outstanding balances and completed referral payouts at a glance.'
  },
  coupons: {
    eyebrow: 'Promotion operations',
    title: 'Coupon performance',
    description: 'Launch controlled offers and monitor usage, discount exposure and post-discount revenue.'
  },
  requests: {
    eyebrow: 'Product intelligence',
    title: 'Request triage',
    description: 'Turn user feedback, content requests and bug reports into an organized action queue.'
  },
  reports: {
    eyebrow: 'Content quality',
    title: 'Question resolution desk',
    description: 'Investigate quiz reports, publish corrections and keep the live question bank trustworthy.'
  },
  telegram: {
    eyebrow: 'Messaging automation',
    title: 'Telegram operations',
    description: 'Control bot credentials, delivery schedules, report routing and connected-user notifications.'
  },
  settings: {
    eyebrow: 'Platform controls',
    title: 'System command center',
    description: 'Manage access policy, maintenance, announcements, defaults and critical service health.'
  }
};

function finNumber(value) {
  return (Number(value) || 0).toLocaleString('en-IN');
}

function finMoney(value) {
  return '₹' + (Number(value) || 0).toLocaleString('en-IN');
}

function finDate(value) {
  try {
    if (!value) return null;
    if (value.toDate) return value.toDate();
    if (value.seconds) return new Date(value.seconds * 1000);
    var date = new Date(value);
    return isNaN(date.getTime()) ? null : date;
  } catch (e) { return null; }
}

function finTodayKey(offsetDays) {
  var now = new Date(Date.now() + (Number(offsetDays) || 0) * 86400000);
  var india = new Date(now.getTime() + (5 * 60 + 30) * 60000);
  return india.toISOString().slice(0, 10);
}

function finExpiryIsCurrent(value) {
  if (!value) return false;
  if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value)) return value >= finTodayKey();
  var expiry = finDate(value);
  return !!(expiry && expiry.getTime() >= Date.now());
}

function finHasActivePaidPlan(user) {
  if (!user || !user.p || !user.p.plan || user.p.plan === 'free' || user.p.status === 'rejected') return false;
  var lifetime = String(user.p.plan).toLowerCase().includes('lifetime');
  return lifetime || finExpiryIsCurrent(user.p.planExpiry);
}

function finHasActiveTrial(user) {
  return !!(user && user.p && user.p.trialExpiry && !user.p.trialSuspended && finExpiryIsCurrent(user.p.trialExpiry));
}

function finSnapshotLabel() {
  if (typeof ADMIN_DATA_HEALTH === 'undefined' || !ADMIN_DATA_HEALTH.lastSuccessfulAt) return 'Snapshot not fully refreshed';
  var date = finDate(ADMIN_DATA_HEALTH.lastSuccessfulAt);
  return date ? 'Data refreshed ' + date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : 'Loaded admin snapshot';
}

function finKpi(icon, label, value, detail, tone) {
  return '<article class="fin-kpi fin-kpi--' + (tone || 'neutral') + '">' +
    '<span class="fin-kpi-icon" aria-hidden="true">' + icon + '</span>' +
    '<div><span class="fin-kpi-label">' + label + '</span>' +
    '<strong>' + value + '</strong><small>' + detail + '</small></div>' +
  '</article>';
}

function finDuplicateTxnGroups() {
  var counts = {};
  (PAYMENTS || []).forEach(function(payment) {
    var key = payment.txnId ? String(payment.txnId).trim().toLowerCase() : '';
    if (key) counts[key] = (counts[key] || 0) + 1;
  });
  return Object.keys(counts).filter(function(key) { return counts[key] > 1; }).length;
}

function finPayoutRows() {
  var refMap = {};
  (USERS || []).forEach(function(user) {
    if (user.p.referredBy) (refMap[user.p.referredBy] = refMap[user.p.referredBy] || []).push(user);
  });
  return Object.keys(refMap).map(function(refUid) {
    var referrer = USERS.find(function(user) { return user.id === refUid; });
    var paidCount = refMap[refUid].filter(function(user) { return user.p.plan && user.p.plan !== 'free'; }).length;
    var earned = paidCount * 10;
    var paid = Number(referrer && referrer.p.payoutPaidAmount) || 0;
    return { eligible: paidCount >= 20, earned: earned, paid: paid, due: Math.max(0, earned - paid) };
  }).filter(function(row) { return row.earned > 0; });
}

function finViewKpis(tab) {
  var users = USERS || [];
  var payments = PAYMENTS || [];
  var verified = payments.filter(function(payment) { return payment.status === 'verified' || payment.status === 'approved'; });
  var pendingPayments = payments.filter(function(payment) { return payment.status === 'pending'; }).length;
  var paidUsers = users.filter(finHasActivePaidPlan).length;
  var now = new Date();
  var sevenDaysAgo = now.getTime() - 7 * 86400000;
  var today = finTodayKey();
  var inSevenDays = finTodayKey(7);

  if (tab === 'analytics') {
    var newSeven = users.filter(function(user) {
      var date = finDate(user.p.createdAt || user.p.requestedAt);
      return date && date.getTime() >= sevenDaysAgo;
    }).length;
    var revenue = verified.reduce(function(sum, payment) { return sum + (Number(payment.amount) || 0); }, 0);
    return [
      finKpi('U', 'Total users', finNumber(users.length), 'All registered accounts', 'blue'),
      finKpi('↗', '7-day growth', finNumber(newSeven), 'New registrations', 'green'),
      finKpi('P', 'Paid users', finNumber(paidUsers), users.length ? Math.round(paidUsers / users.length * 100) + '% conversion' : 'No users yet', 'violet'),
      finKpi('₹', 'Verified revenue', finMoney(revenue), verified.length + ' approved payments', 'amber')
    ];
  }

  if (tab === 'pending') {
    var pendingUsers = users.filter(function(user) { return user.p.status === 'pending'; });
    var duplicate = pendingUsers.filter(function(user) { return user.p.deviceDuplicate || flagsFor(user).length > 0; }).length;
    var oldestDate = pendingUsers.reduce(function(oldest, user) {
      var date = finDate(user.p.requestedAt || user.p.createdAt);
      return date && (!oldest || date < oldest) ? date : oldest;
    }, null);
    var wait = oldestDate ? Math.max(0, Math.floor((now - oldestDate) / 86400000)) + 'd' : '—';
    return [
      finKpi('Q', 'Waiting review', finNumber(pendingUsers.length), 'Accounts in queue', pendingUsers.length ? 'amber' : 'green'),
      finKpi('D', 'Risk signals', finNumber(duplicate), 'Duplicate device or identity', duplicate ? 'red' : 'green'),
      finKpi('N', 'New devices', finNumber(Math.max(0, pendingUsers.length - duplicate)), 'Low-friction reviews', 'blue'),
      finKpi('T', 'Oldest wait', wait, oldestDate ? 'Time since first request' : 'Queue is clear', pendingUsers.length ? 'violet' : 'green')
    ];
  }

  if (tab === 'users') {
    var active = users.filter(function(user) { return user.p.status !== 'pending' && user.p.status !== 'rejected'; }).length;
    var trials = users.filter(finHasActiveTrial).length;
    var suspended = users.filter(function(user) { return user.p.status === 'rejected'; }).length;
    return [
      finKpi('A', 'Active accounts', finNumber(active), 'Approved and operational', 'green'),
      finKpi('P', 'Paid portfolio', finNumber(paidUsers), 'Users on non-free plans', 'blue'),
      finKpi('T', 'Active trials', finNumber(trials), 'Trial access currently granted', 'violet'),
      finKpi('S', 'Suspended', finNumber(suspended), 'Restricted accounts', suspended ? 'red' : 'neutral')
    ];
  }

  if (tab === 'plans') {
    var expiring = users.filter(function(user) {
      return user.p.plan && user.p.plan !== 'free' && user.p.planExpiry && user.p.planExpiry >= today && user.p.planExpiry <= inSevenDays;
    }).length;
    return [
      finKpi('P', 'Published plans', finNumber((PLANS || []).length), 'Available pricing options', 'violet'),
      finKpi('U', 'Paid users', finNumber(paidUsers), 'Current subscribed base', 'blue'),
      finKpi('7', 'Expiring soon', finNumber(expiring), 'Within the next 7 days', expiring ? 'amber' : 'green'),
      finKpi('₹', 'UPI collection', CONFIG && CONFIG.upiId ? 'Ready' : 'Setup needed', CONFIG && CONFIG.upiId ? 'Payment identity configured' : 'Add a UPI ID before launch', CONFIG && CONFIG.upiId ? 'green' : 'red')
    ];
  }

  if (tab === 'payments') {
    var revenueTotal = verified.reduce(function(sum, payment) { return sum + (Number(payment.amount) || 0); }, 0);
    var approvalRate = payments.length ? Math.round(verified.length / payments.length * 100) : 0;
    return [
      finKpi('Q', 'Pending review', finNumber(pendingPayments), 'Transactions awaiting action', pendingPayments ? 'amber' : 'green'),
      finKpi('₹', 'Verified revenue', finMoney(revenueTotal), verified.length + ' successful payments', 'green'),
      finKpi('D', 'Duplicate groups', finNumber(finDuplicateTxnGroups()), 'Repeated transaction IDs', finDuplicateTxnGroups() ? 'red' : 'green'),
      finKpi('%', 'Approval rate', approvalRate + '%', payments.length + ' total submissions', 'blue')
    ];
  }

  if (tab === 'referrals') {
    var referrers = {};
    var referred = 0;
    var converted = 0;
    users.forEach(function(user) {
      if (!user.p.referredBy) return;
      referrers[user.p.referredBy] = true;
      referred++;
      if (user.p.plan && user.p.plan !== 'free') converted++;
    });
    return [
      finKpi('R', 'Active referrers', finNumber(Object.keys(referrers).length), 'Users generating invitations', 'violet'),
      finKpi('U', 'Referred users', finNumber(referred), 'Total attributed signups', 'blue'),
      finKpi('P', 'Paid conversions', finNumber(converted), referred ? Math.round(converted / referred * 100) + '% conversion' : 'No referrals yet', 'green'),
      finKpi('₹', 'Rewards earned', finMoney(converted * 10), 'At ₹10 per paid conversion', 'amber')
    ];
  }

  if (tab === 'payouts') {
    var payoutRows = finPayoutRows();
    var eligible = payoutRows.filter(function(row) { return row.eligible && row.due > 0; }).length;
    var earnedTotal = payoutRows.reduce(function(sum, row) { return sum + row.earned; }, 0);
    var dueTotal = payoutRows.reduce(function(sum, row) { return sum + row.due; }, 0);
    var paidTotal = payoutRows.reduce(function(sum, row) { return sum + row.paid; }, 0);
    return [
      finKpi('E', 'Eligible payouts', finNumber(eligible), 'Unlocked balances to process', eligible ? 'amber' : 'green'),
      finKpi('D', 'Total due', finMoney(dueTotal), 'Outstanding referral rewards', dueTotal ? 'red' : 'green'),
      finKpi('₹', 'Lifetime earned', finMoney(earnedTotal), 'Rewards generated', 'violet'),
      finKpi('P', 'Already paid', finMoney(paidTotal), 'Completed payout value', 'green')
    ];
  }

  if (tab === 'coupons') {
    var activeCoupons = (COUPONS || []).filter(function(coupon) { return couponStatus(coupon).label === 'Active'; }).length;
    var discounts = (REDEMPTIONS || []).reduce(function(sum, redemption) { return sum + (Number(redemption.discountAmount) || 0); }, 0);
    var couponRevenue = (REDEMPTIONS || []).reduce(function(sum, redemption) { return sum + (Number(redemption.finalAmount) || 0); }, 0);
    return [
      finKpi('A', 'Active coupons', finNumber(activeCoupons), (COUPONS || []).length + ' offers configured', 'green'),
      finKpi('R', 'Redemptions', finNumber((REDEMPTIONS || []).length), 'Recorded coupon uses', 'blue'),
      finKpi('D', 'Discount exposure', finMoney(discounts), 'Total value granted', 'amber'),
      finKpi('₹', 'Coupon revenue', finMoney(couponRevenue), 'Collected after discount', 'violet')
    ];
  }

  if (tab === 'requests') {
    var requestList = REQUESTS || [];
    var countStatus = function(status) { return requestList.filter(function(request) { return request.status === status; }).length; };
    var bugs = requestList.filter(function(request) { return request.type === 'bug'; }).length;
    return [
      finKpi('N', 'New requests', finNumber(countStatus('new')), 'Waiting for triage', countStatus('new') ? 'amber' : 'green'),
      finKpi('D', 'Completed', finNumber(countStatus('done')), 'Requests marked done', 'green'),
      finKpi('X', 'Dismissed', finNumber(countStatus('dismissed')), 'Closed without action', 'neutral'),
      finKpi('B', 'Bug reports', finNumber(bugs), 'All-time bug submissions', bugs ? 'red' : 'blue')
    ];
  }

  if (tab === 'reports') {
    var reportList = REPORTS || [];
    var reportCount = function(status) { return reportList.filter(function(report) { return report.status === status; }).length; };
    return [
      finKpi('O', 'Open reports', finNumber(reportCount('open')), 'Questions needing review', reportCount('open') ? 'amber' : 'green'),
      finKpi('F', 'Corrections fixed', finNumber(reportCount('fixed')), 'Published resolutions', 'green'),
      finKpi('X', 'Dismissed', finNumber(reportCount('dismissed')), 'Closed reports', 'neutral'),
      finKpi('Σ', 'Total reports', finNumber(reportList.length), REPORTS_LOADED ? 'Supabase data loaded' : 'Loading report data', 'blue')
    ];
  }

  if (tab === 'telegram') {
    var telegramUsers = TG_USERS || [];
    var enabled = telegramUsers.filter(function(user) { return user.tg.enabled && user.tg.chatId; }).length;
    var todayKey = finTodayKey();
    var ready = telegramUsers.filter(function(user) { return user.tg.digest && user.tg.digest[todayKey]; }).length;
    var coreReady = !!(TG_CONFIG && TG_CONFIG.botToken);
    return [
      finKpi('C', 'Connected users', finNumber(telegramUsers.length), 'Saved Telegram chat IDs', 'blue'),
      finKpi('N', 'Notifications on', finNumber(enabled), 'Enabled delivery audience', 'green'),
      finKpi('T', 'Plans ready today', finNumber(ready), 'Users with a daily digest', 'violet'),
      finKpi('H', 'Bot health', coreReady ? 'Connected' : 'Setup needed', coreReady ? 'Core token is configured' : 'Add the Telegram bot token', coreReady ? 'green' : 'red')
    ];
  }

  var announcement = SETTINGS && SETTINGS.announcement;
  return [
    finKpi('M', 'Maintenance setting', SETTINGS && SETTINGS.maintenance ? 'Flag on' : 'Flag off', SETTINGS && SETTINGS.maintenance ? 'Saved configuration is enabled' : 'Saved configuration is disabled', SETTINGS && SETTINGS.maintenance ? 'amber' : 'green'),
    finKpi('A', 'Approval preference', SETTINGS && SETTINGS.requireApproval ? 'Manual' : 'Risk-based', SETTINGS && SETTINGS.requireApproval ? 'Manual-review preference saved' : 'Risk-based preference saved', SETTINGS && SETTINGS.requireApproval ? 'amber' : 'blue'),
    finKpi('B', 'Announcement', announcement && announcement.active && announcement.text ? 'Live' : 'Hidden', announcement && announcement.text ? 'Broadcast content saved' : 'No active broadcast', announcement && announcement.active ? 'violet' : 'neutral'),
    finKpi('P', 'Plan catalog', finNumber((PLANS || []).length), SETTINGS && SETTINGS.defaultPlanId ? 'Default plan selected' : 'No default plan selected', 'green')
  ];
}

function finViewStatus(tab) {
  if (typeof ADMIN_DATA_HEALTH !== 'undefined' && ADMIN_DATA_HEALTH.errors && ADMIN_DATA_HEALTH.errors.length) {
    return { tone: 'warning', label: 'Partial data', detail: 'Could not refresh: ' + ADMIN_DATA_HEALTH.errors.join(', ') };
  }
  if (tab === 'pending') {
    var pending = (USERS || []).filter(function(user) { return user.p.status === 'pending'; }).length;
    return { tone: pending ? 'warning' : 'healthy', label: pending ? 'Review required' : 'Queue clear', detail: pending ? pending + ' account' + (pending === 1 ? '' : 's') + ' waiting' : 'No registrations waiting' };
  }
  if (tab === 'payments') {
    var paymentQueue = (PAYMENTS || []).filter(function(payment) { return payment.status === 'pending'; }).length;
    return { tone: paymentQueue ? 'warning' : 'healthy', label: paymentQueue ? 'Verification queue' : 'Queue clear', detail: paymentQueue ? paymentQueue + ' transaction' + (paymentQueue === 1 ? '' : 's') + ' waiting' : 'No pending payments in this snapshot' };
  }
  if (tab === 'requests') {
    var requests = (REQUESTS || []).filter(function(request) { return request.status === 'new'; }).length;
    return { tone: requests ? 'warning' : 'healthy', label: requests ? 'Triage required' : 'Inbox clear', detail: requests ? requests + ' new request' + (requests === 1 ? '' : 's') : 'No new requests' };
  }
  if (tab === 'reports') {
    if (REP_EDITING) return { tone: 'active', label: 'Correction editor', detail: 'Editing a live question correction' };
    var reports = (REPORTS || []).filter(function(report) { return report.status === 'open'; }).length;
    return { tone: reports ? 'warning' : 'healthy', label: reports ? 'Quality review' : 'Report queue clear', detail: reports ? reports + ' open report' + (reports === 1 ? '' : 's') : 'No open reports in this snapshot' };
  }
  if (tab === 'telegram') {
    var connected = !!(TG_CONFIG && TG_CONFIG.botToken);
    return { tone: connected ? 'healthy' : 'critical', label: connected ? 'Bot token saved' : 'Configuration required', detail: connected ? 'Telegram credential is available' : 'Bot token is missing' };
  }
  if (tab === 'settings' && SETTINGS && SETTINGS.maintenance) {
    return { tone: 'warning', label: 'Maintenance flag on', detail: 'Saved system configuration is enabled' };
  }
  return { tone: 'healthy', label: 'Snapshot ready', detail: 'Controls use the currently loaded admin data' };
}

function finAction(label, onclick, primary) {
  return '<button class="fin-action ' + (primary ? 'fin-action--primary' : 'fin-action--ghost') + '" type="button" onclick="' + onclick + '">' + label + '</button>';
}

function finViewActions(tab) {
  if (tab === 'pending') return finAction('Search queue', "finFocusControl('pending-search')", true) + finAction('Refresh', 'refreshAdminData()', false);
  if (tab === 'users') return finAction('Find a user', "finFocusControl('user-search')", true) + finAction('Refresh', 'refreshAdminData()', false);
  if (tab === 'plans') return finAction('Create a plan', "finFocusControl('pl-name')", true) + finAction('Refresh', 'refreshAdminData()', false);
  if (tab === 'payments') return finAction('Export CSV', 'exportPaymentsCSV()', true) + finAction(PAY_VIEW === 'reconcile' ? 'Open list' : 'Reconcile', "PAY_VIEW='" + (PAY_VIEW === 'reconcile' ? 'list' : 'reconcile') + "';render()", false);
  if (tab === 'referrals') return finAction('Open payouts', "setTab('payouts')", true) + finAction('Refresh', 'refreshAdminData()', false);
  if (tab === 'payouts') return finAction('View referrals', "setTab('referrals')", true) + finAction('Refresh', 'refreshAdminData()', false);
  if (tab === 'coupons') return finAction('Create coupon', "finFocusControl('cp-code')", true) + finAction('Export redemptions', 'exportRedemptionsCSV()', false);
  if (tab === 'requests') return finAction('Show new', "setRequestFilter('new')", true) + finAction('Refresh', 'refreshAdminData()', false);
  if (tab === 'reports') {
    if (REP_EDITING) return finAction('Back to reports', 'repCancelEdit()', true);
    return finAction('Show open', "repSetFilter('open')", true) + finAction('Refresh reports', 'REPORTS_LOADED=false;loadReportsData()', false);
  }
  if (tab === 'telegram') return finAction('Refresh users', 'TG_CONFIG.loaded=false;loadTelegramData()', true) + finAction('Send controls', "finFocusControl('tg-sendtime-input')", false);
  if (tab === 'settings') return finAction('Check backend', 'finCheckTurboBackend()', true) + finAction('Refresh', 'refreshAdminData()', false);
  return finAction('Refresh snapshot', 'refreshAdminData()', true) + finAction('Review payments', "setTab('payments')", false);
}

function finFocusControl(id) {
  var element = document.getElementById(id);
  if (!element) return;
  element.focus();
  if (typeof element.select === 'function' && element.tagName === 'INPUT') element.select();
  element.scrollIntoView({ behavior: 'smooth', block: 'center' });
}

async function finCheckTurboBackend() {
  await checkTurboBackend();
  var status = document.getElementById('turbo-backend-status');
  if (!status) return;
  status.setAttribute('role', 'status');
  status.setAttribute('tabindex', '-1');
  finFocusControl('turbo-backend-status');
}

function finPrepareLegacyBody(tab, body) {
  var html = String(body == null ? '' : body);
  if (tab === 'analytics') {
    html = html.replace('<h3 class="section-title">Performance overview</h3>', '<h3 class="section-title fin-legacy-summary">Performance overview</h3>');
    html = html.replace(/<div class="stat-row">/g, '<div class="stat-row fin-legacy-summary">');
  } else if (tab === 'coupons') {
    html = html.replace('<div class="recon-grid">', '<div class="recon-grid fin-legacy-summary">');
  } else if (tab === 'telegram') {
    html = html.replace('<div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px;">', '<div class="fin-legacy-summary" style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px;">');
  }
  return html;
}

function finWrapView(tab, body) {
  var stats = document.getElementById('stats');
  if (stats) stats.hidden = true;
  var meta = FIN_VIEW_META[tab] || FIN_VIEW_META.analytics;
  var status = finViewStatus(tab);
  var kpis = finViewKpis(tab).join('');
  var legacyBody = finPrepareLegacyBody(tab, body);
  var liveStatus = document.getElementById('admin-live-status');
  if (liveStatus) liveStatus.textContent = meta.title + ' view updated.';
  return '<div class="fin-view fin-view--' + tab + '">' +
    '<section class="fin-hero" aria-labelledby="fin-' + tab + '-title">' +
      '<span class="fin-hero-orbit fin-hero-orbit--one" aria-hidden="true"></span>' +
      '<span class="fin-hero-orbit fin-hero-orbit--two" aria-hidden="true"></span>' +
      '<div class="fin-hero-copy"><span class="fin-eyebrow">' + meta.eyebrow + '</span>' +
        '<h2 id="fin-' + tab + '-title">' + meta.title + '</h2><p>' + meta.description + '</p>' +
        '<div class="fin-hero-meta"><span class="fin-health fin-health--' + status.tone + '"><i aria-hidden="true"></i>' + status.label + '</span>' +
          '<span>' + status.detail + '</span><span>' + finSnapshotLabel() + '</span></div>' +
      '</div><div class="fin-hero-actions">' + finViewActions(tab) + '</div>' +
    '</section>' +
    '<section class="fin-kpi-grid" aria-label="' + meta.title + ' key metrics">' + kpis + '</section>' +
    '<div class="fin-context-bar"><div><span class="fin-context-dot" aria-hidden="true"></span><strong>Loaded workspace</strong><span>Actions below update production data.</span></div>' +
      '<span class="fin-context-hint">R refreshes data · Ctrl/⌘ K finds a section</span></div>' +
    '<div class="fin-legacy">' + legacyBody + '</div>' +
  '</div>';
}

renderAnalytics = function() { return finWrapView('analytics', FIN_ORIGINAL_RENDERERS.analytics()); };
renderPending = function() { return finWrapView('pending', FIN_ORIGINAL_RENDERERS.pending()); };
renderUsers = function() { return finWrapView('users', FIN_ORIGINAL_RENDERERS.users()); };
renderPlans = function() { return finWrapView('plans', FIN_ORIGINAL_RENDERERS.plans()); };
renderPayments = function() { return finWrapView('payments', FIN_ORIGINAL_RENDERERS.payments()); };
renderReferrals = function() { return finWrapView('referrals', FIN_ORIGINAL_RENDERERS.referrals()); };
renderPayouts = function() { return finWrapView('payouts', FIN_ORIGINAL_RENDERERS.payouts()); };
renderCoupons = function() { return finWrapView('coupons', FIN_ORIGINAL_RENDERERS.coupons()); };
renderRequests = function() { return finWrapView('requests', FIN_ORIGINAL_RENDERERS.requests()); };
renderReports = function() { return finWrapView('reports', FIN_ORIGINAL_RENDERERS.reports()); };
renderTelegram = function() { return finWrapView('telegram', FIN_ORIGINAL_RENDERERS.telegram()); };
renderSettings = function() { return finWrapView('settings', FIN_ORIGINAL_RENDERERS.settings()); };
